apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment #nouveau nom de deploy a creer 
  labels:
    app: nginx #web 
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx #web 
  template:
    metadata:
      labels:
        app: nginx #web 
    spec:
      containers:
      - name: nginx #web 
        image: nginx:latest #nom de l'image à deployer 
        ports:
        - containerPort: 80 # le numero du port au quelle nginx est exposer sur internet
